In [1]:
# Numpy (Numerical in Python) Library

In [2]:
# Numpy is a powerfull libary for mathematical operations.
# We use numpy to create array

In [3]:
# Array is a collection is homogenous elements. (Same Data Type)

In [4]:
# Array's representation is same like list

In [5]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import numpy as np

In [7]:
# Creating first array
li = list([4,6,56,89,'A',True])
arr = np.array([23,5,67,89])

In [12]:
print(li)
print(arr)

[4, 6, 56, 89, 'A', True]
[23  5 67 89]


In [13]:
arr = np.array([45,53,68,89,23.67])

In [14]:
print(arr)

[45.   53.   68.   89.   23.67]


In [15]:
arr = np.array([3,5,35.65,'A','Aman',True])

In [17]:
print(arr)

['3' '5' '35.65' 'A' 'Aman' 'True']


In [18]:
# array , arange , linspace

In [19]:
arr = np.array([34,56,67,83])
print(arr)

[34 56 67 83]


In [20]:
arr = np.arange(2,21,2)
print(arr)

[ 2  4  6  8 10 12 14 16 18 20]


In [21]:
arr = np.linspace(0.5,5,10)
# linspace(start,stop,number_of_Values) # start and stop are included
print(arr)

[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [22]:
arr = np.linspace(0.5,5,25)
print(arr)

[0.5    0.6875 0.875  1.0625 1.25   1.4375 1.625  1.8125 2.     2.1875
 2.375  2.5625 2.75   2.9375 3.125  3.3125 3.5    3.6875 3.875  4.0625
 4.25   4.4375 4.625  4.8125 5.    ]


In [23]:
# Dimensions

In [24]:
# 0thD , 1stD , 2ndD , 3rdD etc
# Array can work on any dimension

In [27]:
arr = np.array(46)
print(arr)
print(np.ndim(arr))
print(arr.shape)

46
0
()


In [28]:
arr = np.array([23,45,67])
print(arr)
print(np.ndim(arr))
print(arr.shape)

[23 45 67]
1
(3,)


In [30]:
arr = np.array([[23,45,67],[56,78,90],[34,89,35]])
print(arr)
print(np.ndim(arr))
print(arr.shape)

[[23 45 67]
 [56 78 90]
 [34 89 35]]
2
(3, 3)


In [31]:
arr = np.array([[[32,45,67]]])
print(arr)
print(np.ndim(arr))
print(arr.shape)

[[[32 45 67]]]
3
(1, 1, 3)


In [32]:
# and so on..