In [1]:
import pandas as pd
import numpy as np

In [36]:
df = pd.read_csv(r"C:\Users\Croma Campus\Downloads\Churn_Modelling.csv")

In [3]:
df.shape

(10000, 14)

In [4]:
df.head(4)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0

In [5]:
df.Geography.unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [6]:
df.Exited

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [7]:
df.groupby('Gender').agg({'Exited':'count'})

Exited
Gender        
Female    4543
Male      5457

In [8]:
df.groupby('Gender').agg({'Exited':'sum'})

Exited
Gender        
Female    1139
Male       898

In [9]:
df.groupby('Geography').agg({'Exited':'count'})

Exited
Geography        
France       5014
Germany      2509
Spain        2477

In [10]:
df.groupby('Geography').agg({'Exited':'sum'})

Exited
Geography        
France        810
Germany       814
Spain         413

In [11]:
 df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [12]:
df = df.drop(columns=['RowNumber', 'CustomerId', 'Surname'])

In [13]:
df.shape

(10000, 11)

In [14]:
df.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [15]:
# LabelEncoder
def labelEncoder(val):
    li = list(df[col].unique())
    return li.index(val)

In [16]:
global col
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].map(labelEncoder)

In [17]:
df.shape

(10000, 11)

In [18]:
df.head()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0       0   42       2       0.00              1   
1          608          1       0   41       1   83807.86              1   
2          502          0       0   42       8  159660.80              3   
3          699          0       0   39       1       0.00              2   
4          850          1       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [19]:
df.Gender.unique()

array([0, 1])

In [20]:
df.Geography.unique()

array([0, 1, 2])

In [21]:
df.head(3)

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0       0   42       2       0.00              1   
1          608          1       0   41       1   83807.86              1   
2          502          0       0   42       8  159660.80              3   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1

In [22]:
X = df.drop(columns=['Exited'])

In [23]:
X.head(3)

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0       0   42       2       0.00              1   
1          608          1       0   41       1   83807.86              1   
2          502          0       0   42       8  159660.80              3   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57

In [24]:
y = df['Exited']

In [25]:
y[:3]

0    1
1    0
2    1
Name: Exited, dtype: int64

In [26]:
X.head(2)

CreditScore  Geography  Gender  Age  Tenure   Balance  NumOfProducts  \
0          619          0       0   42       2      0.00              1   
1          608          1       0   41       1  83807.86              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58

In [27]:
X.columns

Index(['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary'],
      dtype='object')

In [28]:
scale_list = ['CreditScore','Age','Balance','EstimatedSalary']

In [29]:
# Normalization
def normalization(val):
    return (val - X[col].min())/(X[col].max()-X[col].min())

In [30]:
global col
for col in scale_list:
    X[col] = X[col].map(normalization)

In [31]:
X.head()

CreditScore  Geography  Gender       Age  Tenure   Balance  NumOfProducts  \
0        0.538          0       0  0.324324       2  0.000000              1   
1        0.516          1       0  0.310811       1  0.334031              1   
2        0.304          0       0  0.324324       8  0.636357              3   
3        0.698          0       0  0.283784       1  0.000000              2   
4        1.000          1       0  0.337838       2  0.500246              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1         0.506735  
1          0               1         0.562709  
2          1               0         0.569654  
3          0               0         0.469120  
4          1               1         0.395400

In [32]:
for col in scale_list:
    print(col,'\tMIN :',X[col].min(),'\tMAX :',X[col].max())

CreditScore 	MIN : 0.0 	MAX : 1.0
Age 	MIN : 0.0 	MAX : 1.0
Balance 	MIN : 0.0 	MAX : 1.0
EstimatedSalary 	MIN : 0.0 	MAX : 1.0


In [33]:
X.head()

CreditScore  Geography  Gender       Age  Tenure   Balance  NumOfProducts  \
0        0.538          0       0  0.324324       2  0.000000              1   
1        0.516          1       0  0.310811       1  0.334031              1   
2        0.304          0       0  0.324324       8  0.636357              3   
3        0.698          0       0  0.283784       1  0.000000              2   
4        1.000          1       0  0.337838       2  0.500246              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1         0.506735  
1          0               1         0.562709  
2          1               0         0.569654  
3          0               0         0.469120  
4          1               1         0.395400

In [38]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [39]:
df = df.drop(columns=[	'RowNumber',	'CustomerId'	,'Surname'])

In [40]:
df.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [41]:
df.Geography.unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [42]:
df.Gender.unique()

array(['Female', 'Male'], dtype=object)

In [43]:
# One_hot Encoder
def oneHotEncoder(val):
    df[val] = df[col].map(lambda val2:1 if val2==val else 0)

In [44]:
global col
for col in df.select_dtypes(include='object').columns:
    for v in df[col].unique():
        oneHotEncoder(v)

In [45]:
df.shape

(10000, 16)

In [46]:
df.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  France  Spain  Germany  \
0          1               1        101348.88       1       1      0        0   
1          0               1        112542.58       0       0      1        0   
2          1               0        113931.57       1       1      0        0   
3          0               0         93826.63       0       1      0        0   
4          1               1         79084.10       0       0      1        0   

   Female  Male  
0       1     0  
1       1     0  
2       1     0  
3       1     0  
4       1     0

In [47]:
df = df.drop(columns=['Geography' ,	'Gender'])

In [48]:
df.shape

(10000, 14)

In [49]:
df.head(2)

CreditScore  Age  Tenure   Balance  NumOfProducts  HasCrCard  \
0          619   42       2      0.00              1          1   
1          608   41       1  83807.86              1          0   

   IsActiveMember  EstimatedSalary  Exited  France  Spain  Germany  Female  \
0               1        101348.88       1       1      0        0       1   
1               1        112542.58       0       0      1        0       1   

   Male  
0     0  
1     0

In [50]:
scale_col = ['CreditScore','Age','Balance','EstimatedSalary']

In [51]:
# Standardization
def standardization(col):
    df[col] = (df[col]-df[col].mean())/df[col].std()

In [52]:
for col in scale_col:
    standardization(col)

In [53]:
df.shape

(10000, 14)

In [54]:
df.head()

CreditScore       Age  Tenure   Balance  NumOfProducts  HasCrCard  \
0    -0.326205  0.293503       2 -1.225786              1          1   
1    -0.440014  0.198154       1  0.117344              1          0   
2    -1.536717  0.293503       8  1.332987              3          1   
3     0.501496  0.007456       1 -1.225786              2          0   
4     2.063781  0.388852       2  0.785689              1          1   

   IsActiveMember  EstimatedSalary  Exited  France  Spain  Germany  Female  \
0               1         0.021885       1       1      0        0       1   
1               1         0.216523       0       0      1        0       1   
2               0         0.240675       1       1      0        0       1   
3               0        -0.108912       0       1      0        0       1   
4               1        -0.365258       0       0      1        0       1   

   Male  
0     0  
1     0  
2     0  
3     0  
4     0

In [55]:
for col in scale_col:
    print(col,'\tMin :',df[col].min(),'\tMAX :',df[col].max())

CreditScore 	Min : -3.1093486092022866 	MAX : 2.0637805704342176
Age 	Min : -1.9948690030029612 	MAX : 5.0609438917871215
Balance 	Min : -1.2257863774930713 	MAX : 2.7951835520450588
EstimatedSalary 	Min : -1.7401808779180206 	MAX : 1.7371132679331918


In [56]:
df.head(2)

CreditScore       Age  Tenure   Balance  NumOfProducts  HasCrCard  \
0    -0.326205  0.293503       2 -1.225786              1          1   
1    -0.440014  0.198154       1  0.117344              1          0   

   IsActiveMember  EstimatedSalary  Exited  France  Spain  Germany  Female  \
0               1         0.021885       1       1      0        0       1   
1               1         0.216523       0       0      1        0       1   

   Male  
0     0  
1     0

In [57]:
# Remove Outlier
for col in scale_col:
    df = df[df[col]>-3]
    df = df[df[col]< 3]

In [58]:
df.shape

(9859, 14)

In [59]:
X = df.drop(columns=['Exited'])

In [60]:
X.head(2)

CreditScore       Age  Tenure   Balance  NumOfProducts  HasCrCard  \
0    -0.326205  0.293503       2 -1.225786              1          1   
1    -0.440014  0.198154       1  0.117344              1          0   

   IsActiveMember  EstimatedSalary  France  Spain  Germany  Female  Male  
0               1         0.021885       1      0        0       1     0  
1               1         0.216523       0      1        0       1     0

In [61]:
y = df['Exited']

In [63]:
y.head(2)

0    1
1    0
Name: Exited, dtype: int64

In [69]:
X_train = X.iloc[0:int(df.shape[0]*0.8)] 
X_test  = X.iloc[int(df.shape[0]*0.8)+1 : ]  

In [74]:
X_train.head(2)

CreditScore       Age  Tenure   Balance  NumOfProducts  HasCrCard  \
0    -0.326205  0.293503       2 -1.225786              1          1   
1    -0.440014  0.198154       1  0.117344              1          0   

   IsActiveMember  EstimatedSalary  France  Spain  Germany  Female  Male  
0               1         0.021885       1      0        0       1     0  
1               1         0.216523       0      1        0       1     0

In [71]:
X_train.shape

(7887, 13)

In [76]:
X_test.head(2)

CreditScore       Age  Tenure   Balance  NumOfProducts  HasCrCard  \
8000     0.998116 -0.278590       8  0.418566              2          1   
8001     0.584266 -0.659985       9 -1.225786              2          1   

      IsActiveMember  EstimatedSalary  France  Spain  Germany  Female  Male  
8000               1         1.401542       0      0        1       0     1  
8001               0         0.458795       0      1        0       0     1

In [77]:
X_test.shape

(1971, 13)

In [78]:
y_train = y[0:int(df.shape[0]*0.8)]
y_test  = y[int(df.shape[0]*0.8)+1 : ]

In [80]:
# !pip install scikit-learn

In [81]:
from sklearn.linear_model import LogisticRegression

In [90]:
model = LogisticRegression(max_iter = 1000)

In [91]:
model

LogisticRegression(max_iter=1000)

In [92]:
model.fit(X_train,y_train)

LogisticRegression(max_iter=1000)

In [94]:
y_pred = model.predict(X_test)

In [104]:
import numpy as np

In [105]:
y_test = np.array(y_test)

In [108]:
y_test[0:10] , y_pred[0:10]

(array([0, 0, 0, 1, 0, 0, 0, 1, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0]))

In [109]:
count = 0
for i in range(len(y_test)):
    if y_test[i]==y_pred[i]:
        count+=1

In [111]:
count/len(y_test)*100

81.48148148148148

In [112]:
from sklearn.metrics import accuracy_score

In [113]:
print("Accuracy :",accuracy_score(y_test,y_pred)*100)

Accuracy : 81.48148148148148


In [114]:
from sklearn.metrics import confusion_matrix

In [115]:
confusion_matrix(y_pred,y_test)

array([[1505,  284],
       [  81,  101]])

In [118]:
284+101

385

In [119]:
101/385*100

26.233766233766232